const DEFAULT_ERROR_MSG = 'Unhandled Error'
const DEFAULT_ERROR_STATUS_CODE = 500
const DEFAULT_ERROR_CODE = 'GENERIC_ERROR_CODE'

const REQUEST_ID_HEADER_KEY = 'X-Request-Id'
const SESSION_ID_HEADER_KEY = 'X-Session-Id'

export {
  DEFAULT_ERROR_MSG,
  DEFAULT_ERROR_STATUS_CODE,
  DEFAULT_ERROR_CODE,

  REQUEST_ID_HEADER_KEY,
  SESSION_ID_HEADER_KEY
}
